#!/bin/bash

jboss-cli.sh -c --controller=${OPENSHIFT_WILDFLY_IP}:${OPENSHIFT_WILDFLY_MANAGEMENT_HTTP_PORT} '/subsystem=undertow/configuration=handler/file=image-content/:add(directory-listing=false,path=${jboss.home.dir}/uploads/cposimg)'
jboss-cli.sh -c --controller=${OPENSHIFT_WILDFLY_IP}:${OPENSHIFT_WILDFLY_MANAGEMENT_HTTP_PORT} '/subsystem=undertow/server=default-server/host=default-host/location=\/images/:add(handler=image-content)'

#'/subsystem=undertow/configuration=handler/file=image-content/:add(directory-listing=false,path=${jboss.home.dir}/uploads/cposimg)'
#'/subsystem=undertow/server=default-server/host=default-host/location=\/images/:add(handler=image-content)'
